### ISSUE TITLE
Scripts use /bin/sh but depends on non-posix extensions

### ISSUE THREAD

**Issue by hen6003** [heyjuvi/avizo#48]
This causes lightctl to fail on voidlinux, as line 116 causes the script to crash.
Replacing /bin/sh with /bin/bash fixes this

**Comment by jirutka** [comment]
https://github.com/misterdanb/avizo/blob/67af5fd55279c25546d79cebdb4cb73440093082/lightctl#L116

added in #44. Moreover, it’s unnecessary, this can be easily written as `light=${light%.*}`.

**Comment by misterdanb** [comment]
@jirutka Have you tested the suggested change? I'm not a bash/sh expert, so I rely on some suggestions. Do you want to make a pull request? (I can also just integrate the change if it's really that simple)
